import Head from "next/head";

import Footer from "./Footer";
import Header from "./Header";

import styles from "@/styles/components/Page.module.scss";

function Page({ children }: { children: JSX.Element | JSX.Element[] }) {
  return (
    <>
      <Head>
        <title>Color Selector</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.app}>
        <Header />
        <main>{children}</main>
        <Footer />
      </div>
    </>
  );
}

export default Page;
